packages:
  - backend
  - frontend

onlyBuiltDependencies:
  - '@nestjs/core'
<<<<<<< HEAD
  - '@prisma/engines'
  - bcrypt
  - esbuild
=======
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
>>>>>>> 290370a19af069c11dcba02e6949aa48c45160ef
  - prisma
  - sharp
  - unrs-resolver
