services:
  # Le Serveur Backend (NestJS)
  - type: web
    name: wapibei-backend
    env: docker
    rootDir: backend
    plan: free # ou 'starter' pour la prod
    healthCheckPath: /api/categories # Endpoint pour vérifier que le serveur est en ligne
    envVars:
      # L'URL de votre base de données Neon (à configurer dans le Dashboard Render ou via un secret)
      - key: DATABASE_URL
        sync: false
      
      # Variables d'environnement standard
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      
      # Variables de sécurité (générées automatiquement ou à remplacer dans le dashboard)
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      
      # URL du Frontend
      - key: FRONTEND_URL
        value: https://wapibei.com
