@baseUrl = http://localhost:4000

# ==============================================================================
# 1. CONNEXION DU VENDEUR
# ==============================================================================
# @name loginVendor
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "forcenzulo@gmail.com", 
  "password": "Obed@321"
}

###

@vendorToken = {{loginVendor.response.body.access_token}}

# Note : N'oublie pas d'aller activer l'option SMS pour ce vendeur sur le site web
# (Paramètres > Notifications > SMS pour Commandes).

# ==============================================================================
# 2. CONNEXION DU CLIENT (L'ACHETEUR)
# ==============================================================================
# @name loginClient
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "acheteur@test.com",
  "password": "ton-mot-de-passe"
}

###

@clientToken = {{loginClient.response.body.access_token}}


# ==============================================================================
# 3. RÉCUPÉRER UN PRODUIT
# ==============================================================================
# Récupérer quelques produits publics (ex: meilleures ventes)
# @name getProducts
GET {{baseUrl}}/products/best-sellers
Content-Type: application/json

###

# On stocke automatiquement l'ID du premier produit de la liste
@productId = {{getProducts.response.body.data[0].id}}


# ==============================================================================
# 4. PASSER UNE COMMANDE (DÉCLENCHE LE SMS !)
# ==============================================================================
# Envoie la requête en utilisant le token du client et l'ID du produit récupéré
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{clientToken}}

{
  "productId": "{{productId}}",
  "customerName": "Client Testeur",
  "customerPhone": "243000000000",
  "deliveryAddress": "Goma, Centre Ville"
}
